name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
    paths:
      - grammar.js
      - src/**
      - bindings/**
      - queries/**
      - test/**

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: tree-sitter/setup-action/cli@v2
      - run: tree-sitter test
